status=passed
tests=1
failures=0
errors=0
skipped=0
sigtestTool=jakarta.tck:sigtest-maven-plugin:2.6
signatureFile=cdi-api-jdk17.sig
signatureSource=cdi-tck-core-impl-4.1.0.jar
bootCpRelease=17
packages=jakarta.decorator,jakarta.enterprise.**,jakarta.interceptor
apiArtifacts=jakarta.annotation-api-3.0.0.jar,jakarta.el-api-6.0.0.jar,jakarta.enterprise.cdi-api-4.1.0.jar,jakarta.enterprise.lang-model-4.1.0.jar,jakarta.inject-api-2.0.1.jar,jakarta.interceptor-api-2.2.0.jar
report=signature-test-report.txt
