name: Java CI
on:
  push:
    branches:
      - main
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - main
      - '[1-9]+.[0-9]+.x'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '17']
    steps:
       # https://github.com/actions/virtual-environments/issues/709
      - name: Free disk space
        run: |
         sudo rm -rf "/usr/local/share/boost"
         sudo rm -rf "$AGENT_TOOLSDIRECTORY"
         sudo apt-get clean
         df -h
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Optional setup step
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
        run: |
          [ -f ./setup.sh ] && ./setup.sh || true
      - name: Build with Gradle
        run: |
          # Awful hack for kapt and JDK 17 See https://youtrack.jetbrains.com/issue/KT-45545
          if [ ${{ matrix.java }} == 17 ]; then export GRADLE_OPTS="-Dorg.gradle.jvmargs=--illegal-access=permit"; fi
          ./gradlew dependencyUpdates check --no-daemon --parallel --continue
        env:
           TESTCONTAINERS_RYUK_DISABLED: true
#      - name: Publish Test Report
#        if: always()
#        uses: mikepenz/action-junit-report@v2
#        with:
#          check_name: Java CI / Test Report (${{ matrix.java }})
#          report_paths: '**/build/test-results/test/TEST-*.xml'
